# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: generate-selector
        name: Selector commands updated?
        language: script
        entry: generate_selector.py
        pass_filenames: no
        always_run: yes
