name: RAPIDS
title: RAPIDS
baseurl: "/rapidsai-staging"
postsurl: "https://rapidsai.github.io/site-data/posts.json"
exclude: ['_drafts', 'README.md', '.gitignore', 'CNAME']
plugins:
  - jekyll-redirect-from