# Description: Ensures the generated files for the selector are up to date in
# each PR. Based off of work from AJ Schmidt:
# https://github.com/rapidsai/docker/blob/branch-0.18/.github/workflows/generated-files.yml

name: generated-files

on: pull_request

jobs:
  up-to-date:
    name: up-to-date
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate new selector files
        run: |
          ./generate_selector.py
      - name: Check diffs
        run: |
          git diff
          git diff --exit-code --quiet
